FROM mariadb:11

RUN apt-get update && apt-get install -y \
    mariadb-test \
    ntp \
    pv \
    socat \
    htop \
    innotop \
    vim \
    easy_install \
    mailutils \
    bind-utils \
    sysstat \
    net-tools \
    telnet \
    openssl \
    lm_sensors \
    ipmitool \
    lm-sensors
