parameters:
  - name: phpVersion
    type: string
  - name: nodeVersion
    type: string
  - name: npmCacheDir
    type: string
  - name: composerCacheDir
    type: string


steps:
  - checkout: self
    displayName: 'Checkout source code'

  - script: |
      sudo update-alternatives --set php /usr/bin/php$(PHP_VERSION)
      sudo update-alternatives --set phar /usr/bin/phar$(PHP_VERSION)
      sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(PHP_VERSION)
      sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(PHP_VERSION)
      sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(PHP_VERSION)
      php -version
    displayName: 'Use PHP version ${{ parameters.phpVersion }}'
    env:
      PHP_VERSION: ${{ parameters.phpVersion }}

  - script: php -v
    displayName: 'Check PHP version'

  - script: |
      composer install --no-interaction --prefer-dist --no-progress
    displayName: 'Install Composer Dev Dependencies'
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      npm ci
      npm run build
    displayName: 'Install Node Dependencies and Build Assets'
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      cp .env.testing .env
      php artisan key:generate
    displayName: 'Set Up Environment'
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      php artisan config:clear
      php artisan route:clear
      php artisan cache:clear
      php artisan config:cache
    displayName: 'Optimize Laravel Config'
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      echo "Creating temporary database for this pipeline..."
      mariadb -h mariadb -u root -p"$(ROOT_USER_PASSWORD)" -e "DROP DATABASE IF EXISTS testing;"
      mariadb -h mariadb -u root -p"$(ROOT_USER_PASSWORD)" -e "CREATE DATABASE IF NOT EXISTS testing;"
    displayName: 'Create CI database'
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      php artisan migrate --force
      php artisan db:seed
    displayName: 'Run Database Seeders & Migrations'
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      php artisan test
    displayName: 'Run Tests'
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      echo "Removing dev dependencies for production artifact..."
      composer install --no-dev --optimize-autoloader --classmap-authoritative
    displayName: 'Prune Composer Dev Dependencies'
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      echo "Removing node_modules to shrink artifact..."
      rm -rf $(Build.SourcesDirectory)/node_modules
    displayName: 'Remove Node Modules'

  - script: |
      echo "Deleting temporary database for this pipeline..."
      mariadb -h mariadb -u root -p"$(ROOT_USER_PASSWORD)" -e "DROP DATABASE IF EXISTS testing;"
    displayName: 'Delete CI database'
    workingDirectory: $(Build.SourcesDirectory)

  # -------------------------------
  # Package the production artifact
  # -------------------------------

  - task: CopyFiles@2
    displayName: "Copy files to the artefact staging directory"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)"
      Contents: |
        **/*
        !node_modules/**
        !.git/**
        !storage/**
        !documentation/**
        !docker/**
        !azure-pipelines.yml
        !docker-compose.yml
        !documentation.html
        !CHANGELOG.md
        !README.md
        !.env.testing
        !.env.example
        !.env.local
        !.env
      TargetFolder: "$(Build.ArtifactStagingDirectory)/tmp"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/tmp"
      includeRootFolder: false
      archiveType: 'tar'
      tarCompression: 'gz' # Creates a .tar.gz file
      archiveFile: '$(Build.ArtifactStagingDirectory)/laravel-prod.tar.gz'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/laravel-prod.tar.gz'
      artifact: 'laravel-prod-tar'
      publishLocation: 'pipeline'
