trigger:
  - feature/cicd
#  - main
#  - develop

pool:
  name: Default

variables:
  PHP_VERSION: '8.5'
  NODE_VERSION: '18.x'
  NPM_CACHE_DIR: $(Pipeline.Workspace)/.npm
  COMPOSER_CACHE_DIR: $(Pipeline.Workspace)/.composer/cache
  COMPOSER_NO_INTERACTION: 1

stages:
  - stage: build_test_stage
    displayName: 'Build Dependencies and Run Tests'
    jobs:
      - job: build_test_job
        displayName: 'Build Dependencies and Run Tests'
        steps:
          - template: ./templates/build.yml
            parameters:
              phpVersion: $(PHP_VERSION)
              nodeVersion: $(NODE_VERSION)
              npmCacheDir: $(NPM_CACHE_DIR)
              composerCacheDir: $(COMPOSER_CACHE_DIR)

  - stage: build_deploy_stage
    displayName: 'Deploy artifact to server'
    dependsOn:
      - build_test_stage
    condition: succeeded()
    jobs:
      - job: Deploy
        steps:
          - template: ./templates/deploy-test.yml
            parameters:
              sshEndpoint: $(SSH_ENDPOINT)
              deploymentRoot: $(DEPLOYMENT_ROOT)
